### ISSUE TITLE
Create the basic website

### ISSUE THREAD

**Issue by prophen** [PopSchools/popschools.org#7]
# Statement

**As a website, I would like to have navigation to essential webpages so users can learn about PopSchools activities**

# Acceptance criteria

I know that this story is complete when:

1. The home page renders
2. Links exist to:
   - sponsors.html
   - contributors.html
   - about.html
   - become a sponsor

# Notes and additional context

There's only a placeholder site up at popschools.org. It's time to start building the actual site to share information about PopSchools.

**Comment by AzaniaBG** [comment]
I can get to work on this! Shall I start with wireframes? @prophen

**Comment by Yusadolat** [comment]
Hey @prophen Can I have access to the Design/Wireframe I'd like to pick up some issues.
